name: "curl api"

on: 
  workflow_dispatch:

jobs:
  curl:
    name: "curl create pr"
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@master
        - name: curl
        uses: enflo/curl-action@master
        with:
            curl: |
            curl -L \
                -X POST \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer <YOUR-TOKEN>" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                https://api.github.com/repos/OWNER/REPO/pulls \
                -d '{"title":"Amazing new feature","body":"Please pull these awesome changes in!","head":"octocat:new-feature","base":"master"}'