name: "curl api"

on: 
  workflow_dispatch:

jobs:
  curl:
    name: "curl create pr"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: curl
        uses: enflo/curl-action@master
        with:
          curl: |
            abc
            