name: "Màj qualif"

on: 
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * *"   # Tous les jours, à 7h du matin

jobs:
  trigger-scalingo:
    name: "Lancement job Scalingo"
    runs-on: ubuntu-latest
    steps:
    - uses: scalingo-community/setup-scalingo@v0.1.1
      with:
        region: 'osc-secnum-fr1'
        api_token: ${{ secrets.scalingo_api_token }}
        app_name: 'brap-publi'
    
    - run: scalingo run /bin/bash scalingo_entrypoint.sh
  
  create-pr:
    name: "Création PR"
    runs-on: ubuntu-latest
    needs: trigger-scalingo
    steps:
      - name: "Call API Github"
        uses: indiesdev/curl@v1.1
        with:
          method: "POST"
          url: https://api.github.com/repos/${{ github.repository }}/pulls
          accept: 200,201,204,422 # 422 if PR already exists
          headers: '{ "Accept": "application/vnd.github+json", "X-GitHub-Api-Version": "2022-11-28" }'
          params: '{}'
          # PR de qualif -> prod-clone
          body: '{"title":"MEP","body":"Mise en prod des données de la qualif.","head":"qualif","base":"prod-clone"}'
          timeout: 1000
          bearer-token: ${{ secrets.PAT }}
          log-response: true
          retries: 3
