name: "Mise à jour de la qualif"

on: 
  workflow_dispatch:
  schedule:
    - cron: "20 * * * *"   # Toutes les heures, à la minute 20
jobs:
  trigger-scalingo:
    name: "Lancement job Scalingo"
    runs-on: ubuntu-latest
    steps:
    - uses: scalingo-community/setup-scalingo@v0.1.1
      with:
        region: 'osc-secnum-fr1'
        api_token: ${{ secrets.scalingo_api_token }}
        app_name: 'brap-publi'
    
    - run: scalingo run /bin/bash scalingo_entrypoint.sh
