name: "Mise à jour de la qualif"

on: workflow_dispatch

jobs:
  maj-qualif:

    runs-on: ubuntu-latest
    steps:
    - uses: scalingo-community/setup-scalingo@v0.1.1
      with:
        region: 'osc-secnum-fr1'
        api_token: ${{ secrets.scalingo_api_token }}
        app_name: 'brap-publi'
    
    - run: "pwd && ls"
